# Generated by Django 3.2.3 on 2021-06-05 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LOGIN',
            fields=[
                ('USER_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('FIRST_NAME', models.CharField(max_length=64)),
                ('LAST_NAME', models.CharField(max_length=64)),
                ('EMAIL', models.EmailField(max_length=320)),
                ('PASSWORD', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='STANDUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRST_NAME', models.CharField(max_length=64)),
                ('LAST_NAME', models.CharField(max_length=64)),
                ('SECONDS_UNTIL_LAST_STAND', models.IntegerField()),
                ('SITTING', models.BooleanField()),
                ('STANDING', models.BooleanField()),
                ('USER_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='standup_app.login')),
            ],
        ),
    ]
