# Generated by Django 3.2.3 on 2021-06-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standup_app', '0002_auto_20210625_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='time_standing',
            field=models.FloatField(),
        ),
    ]
