# Generated by Django 3.2.3 on 2021-06-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standup_app', '0003_alter_profile_time_standing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='time_standing',
            field=models.FloatField(default=2.0),
        ),
    ]
